### ISSUE TITLE
Support for Grafana v9

### ISSUE THREAD

**Issue by carlosflorencio** [blackcowmoo/Grafana-Google-Analytics-DataSource#50] opened 2022-06-20 09:01 UTC
Hi, 

Can't install the plugin on the Grafana Cloud due to the plugin not supporting the new version (9).
 
<img width="816" alt="image" src="https://user-images.githubusercontent.com/1500881/174565987-884537eb-2f14-45ca-b263-6f5f72fe4743.png">

**Comment by lcc3108** [comment] 2022-06-20 22:51
The application could not be made because the grafana v9 came out after the plug-in was submitted.

If there are no major changes related to the plug-in in Grafana, it will be released soon.

This is not a bug, so I changed it to an enhancement label.

**Comment by carlosflorencio** [comment] 2022-06-21 08:16
Cool @lcc3108 , thanks 😀 .

**Comment by carlosflorencio** [comment] 2022-06-29 07:24
👌 :)

**Comment by ajimix** [comment] 2022-07-04 13:25
Waiting for this as well 😬

**Comment by MarioAzulay** [comment] 2022-07-22 06:08
Patiently waiting ⏳ 😅 (any ETA?)

**Comment by dennys** [comment] 2022-08-03 02:58
Is it a goold idea to change the dependency to "Grafana >=7.3.x" only?
I find some plugins (ex: Zabbix) only assign the minium version.

**Comment by interfink** [comment] 2022-08-09 19:56
if you need a tester please let me know

**Comment by 50l3r** [comment] 2022-09-07 10:05
Hi guys,

Any news on this? Can i force plugin install into my grafana 9.0 instance?

**Comment by Trilliant-JP** [comment] 2022-09-08 21:47
Also really wanting to try this out - using Grafana 9.1.3.  If you can remove the maximum version number, that'll be awesome, thanks!

**Comment by guillemc23** [comment] 2022-09-25 23:46
Any news on this? Can't wait!

**Comment by jonfairbanks** [comment] 2022-09-29 00:25
@lcc3108 Is this a change that could be merged?

**Comment by 1stdevfriend** [comment] 2022-10-14 10:18
Patiently Waiting :sweat_smile: :hourglass: @lcc3108

**Comment by 1stdevfriend** [comment] 2022-10-14 10:23
I'm literally tried patching up my Prometheus is going to wait patiently now

![image](https://user-images.githubusercontent.com/27912312/195824478-38fe576a-c832-4e62-a423-5b03cfee0369.png)

**Comment by Farooq-chalktalk** [comment] 2022-11-08 14:03
Waiting on this @lcc3108. Thank you!

**Comment by xen** [comment] 2022-11-09 16:35
Hello, there! I'm pretty new to Grafana and just testing does it fits our very needs. I'm ok with waiting for the new version to be released. It is totally ok, but I want to see it in action. 

Is it ok if I choose the earlier version? Is it a good approach?

**Closed** 2023-05-01 12:17 UTC
Labels: enhancement
